# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.mail_helper.vk_mail_helper_factory:
        class: AppBundle\Service\MailHelper\VkMailHelper\VkMailHelperFactory
        arguments: ['@service_container']

    app.oauth.vk_client_factory:
        class: AppBundle\Service\OauthClientAuthentication\VkClient\OauthVkClientFactory
        arguments: ['@service_container', '@request_stack']

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.security.vk_authenticator:
        class: AppBundle\Security\VkAuthenticator
        arguments: ['@app.oauth.vk_client_factory', '@service_container', '@doctrine.orm.entity_manager', '@app.mail_helper.vk_mail_helper_factory', '@router']

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }